apiVersion: v1
kind: Secret
metadata:
  name: codism-file-storage-secret
  namespace: codism-prod
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:mysql://codism-mysql:3306/codism_file_storage?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&connectTimeout=5000&socketTimeout=10000"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "afterlike6937"
