apiVersion: v1
kind: Service
metadata:
  name: codism-file-storage
  namespace: codism-prod
spec:
  type: NodePort
  selector:
    app: codism-file-storage
  ports:
    - port: 8084
      targetPort: 8084
      nodePort: 30084
